plugins:
- name: Camera
  onLoad: false
  pluginClass: inswave.wmatrix.base.plugin.camera.CameraLauncher
- name: NetworkStatus
  onLoad: true
  pluginClass: inswave.wmatrix.base.plugin.networkinformation.NetworkManager
- name: WMatrixProviderPlugin
  onLoad: false
  pluginClass: inswave.wmatrix.base.plugin.provider.WMatrixProviderPlugin
- name: AppPlugin
  onLoad: false
  pluginClass: wmatrix.plugin.app.AppPlugin
