plugins:
- name: Camera
  onLoad: false
  pluginClass: inswave.wmatrix.base.plugin.camera.CameraLauncher
- name: NetworkStatus
  onLoad: true
  pluginClass: inswave.wmatrix.base.plugin.networkinformation.NetworkManager
- name: WMatrixProviderPlugin
  onLoad: false
  pluginClass: inswave.wmatrix.base.plugin.provider.WMatrixProviderPlugin
- name: ScreenRecorderPlugin
  onLoad: false
  pluginClass: wmatrix.plugin.screenrecorder.ScreenRecorderPlugin
- name: MiscPlugin
  onLoad: true
  pluginClass: wmatrix.plugin.misc.MiscPlugin
- name: WebSquarePlugin
  onLoad: false
  pluginClass: wmatrix.plugin.websquare.WebSquarePlugin
