wmatrix:
  active: product
  profiles:
    product:
      applicationId: inswave.wmatrix.template
      appName: WMatrix (Product)
      appVersion: 0.0.1
      appVersionCode: 4
      minSdkVersion: 21
      useServerSelectScreen: false
      server:
      - name: W-Matrix Sample
        appId: inswave.wmatrix.testcase
        url: http://whybrid.inswave.kr:8088
      - name: W-Matrix Release
        appId: ''
        url: http://192.168.151.113:8080
    tst:
      applicationId: inswave.wmatrix.template.tst
      appName: WMatrix (Test)
      appVersion: 0.0.1
      appVersionCode: 1
      minSdkVersion: 21
      useServerSelectScreen: true
      server:
      - name: W-Matrix Sample
        appId: inswave.wmatrix.testcase
        url: http://whybrid.inswave.kr:8088
      - name: W-Matrix Test
        appId: ''
        url: http://192.168.151.113:8080
    develop:
      applicationId: inswave.wmatrix.template.dev
      appName: WMatrix (Dev)
      appVersion: 0.0.1
      appVersionCode: 1
      minSdkVersion: 21
      useServerSelectScreen: true
      server:
      - name: W-Matrix Sample
        appId: inswave.wmatrix.testcase
        url: http://whybrid.inswave.kr:8088
      - name: W-Matrix Dev
        appId: ''
        url: http://192.168.151.113:8080
      - name: WMRM
        appId: inswave.wmatrix.mrm
        url: http://192.168.151.51:9080/
